export enum InGameEvents {
    GameStart = 'gameStart',
    GameStarted = 'gameStarted',
    GameOver = 'gameOver',
    GameForceStopped = 'gameForceStopped',
    LoadGameStatistics = 'loadGameStatistics',

    TurnStart = 'turnStart',
    TurnStarted = 'turnStarted',
    TurnEnd = 'turnEnd',
    TurnEnded = 'turnEnded',
    TurnTransitionEnded = 'turnTransitionEnded',
    TurnTimeout = 'turnTimeout',
    TurnForcedEnd = 'turnForcedEnd',
    TurnManualEnd = 'turnManualEnd',

    PlayerEndTurn = 'playerEndTurn',
    PlayerAbandonGame = 'playerAbandonGame',
    PlayerAbandoned = 'playerAbandoned',
    PlayerJoinInGameSession = 'playerJoinInGameSession',
    PlayerJoinedInGameSession = 'playerJoinedInGameSession',
    PlayerLeaveInGameSession = 'playerLeaveInGameSession',
    PlayerLeftInGameSession = 'playerLeftInGameSession',
    PlayerMove = 'playerMove',
    PlayerMoved = 'playerMoved',
    PlayerCombatAction = 'playerCombatAction',
    PlayerCombatResult = 'playerCombatResult',
    PlayerUpdated = 'playerUpdated',
    PlayerActionUsed = 'playerAvailableActionsUpdated',
    PlayerReachableTiles = 'playerReachableTiles',
    PlayerAvailableActions = 'playerAvailableActions',
    PlayerSanctuaryRequest = 'playerSanctuaryRequest',
    PlayerSanctuaryAction = 'playerSanctuaryAction',
    PlayerBonusesChanged = 'playerBonusesChanged',

    OpenSanctuary = 'openSanctuary',
    SanctuaryActionFailed = 'sanctuaryActionFailed',
    SanctuaryActionSuccess = 'sanctuaryActionSuccess',

    ToggleAdminMode = 'toggleAdminMode',
    AdminModeToggled = 'adminModeToggled',
    PlayerTeleport = 'playerTeleport',
    PlayerTeleported = 'playerTeleported',

    ToggleDoorAction = 'toggleDoorAction',
    AttackPlayerAction = 'attackPlayerAction',
    CombatChoice = 'combatChoice',
    CombatPostureSelected = 'combatPostureSelected',
    CombatStarted = 'combatStarted',
    CombatNotification = 'combatNotification',
    CombatTimerUpdate = 'combatTimerUpdate',
    CombatTileEffect = 'combatTileEffect',
    CombatNewRoundStarted = 'combatNewRoundStarted',
    CombatVictory = 'combatVictory',
    CombatEnded = 'combatEnded',
    CombatAbandon = 'combatAbandon',
    CombatCountChanged = 'combatCountChanged',
    CombatWinsChanged = 'combatWinsChanged',
    CombatLossesChanged = 'combatLossesChanged',
    CombatDrawsChanged = 'combatDrawsChanged',
    CombatTimerRestart = 'combatTimerRestart',
    DoorToggled = 'doorToggled',
    PlayerHealthChanged = 'playerHealthChanged',
    LeftInGameSessionAck = 'leftInGameSessionAck',
}
