export enum InGameEvents {
    GameStart = 'game-start',
    GameStarted = 'game-started',
    GameOver = 'game-over',
    GameForceStopped = 'game-force-stopped',

    TurnStart = 'turn-start',
    TurnStarted = 'turn-started',
    TurnEnd = 'turn-end',
    TurnEnded = 'turn-ended',
    TurnTransitionEnded = 'turn-transition-ended',
    TurnManualEnd = 'turn-manual-end',

<<<<<<< HEAD
    PlayerEndTurn = 'player-end-turn',
    PlayerJoinInGameSession = 'player-join-in-game-session',
    PlayerJoinedInGameSession = 'player-joined-in-game-session',
    PlayerLeaveInGameSession = 'player-leave-in-game-session',
    PlayerLeftInGameSession = 'player-left-in-game-session',
    PlayerMove = 'player-move',
    PlayerMoved = 'player-moved',
    PlayerCombatResult = 'player-combat-result',
    PlayerUpdated = 'player-updated',
    PlayerActionUsed = 'player-available-actions-updated',
    PlayerReachableTiles = 'player-reachable-tiles',
    PlayerAvailableActions = 'player-available-actions',

    ToggleAdminMode = 'toggle-admin-mode',
    AdminModeToggled = 'admin-mode-toggled',
    PlayerTeleport = 'player-teleport',
    PlayerTeleported = 'player-teleported',
    
    ToggleDoorAction = 'toggle-door-action',
    AttackPlayerAction = 'attack-player-action',
    CombatChoice = 'combat-choice',
    CombatPostureSelected = 'combat-posture-selected',
    CombatStarted = 'combat-started',
    CombatNewRoundStarted = 'combat-new-round-started',
    CombatVictory = 'combat-victory',
    CombatAbandon = 'combat-abandon',
    CombatCountChanged = 'combat-count-changed',
    CombatWinsChanged = 'combat-wins-changed',
    CombatLossesChanged = 'combat-losses-changed',
    CombatDrawsChanged = 'combat-draws-changed',
    CombatTimerRestart = 'combat-timer-restart',
    DoorToggled = 'door-toggled',
    PlayerHealthChanged = 'player-health-changed',
    LeftInGameSessionAck = 'left-in-game-session-ack',
    LoadGameStatistics = 'load-game-statistics',
=======
    PlayerEndTurn = 'playerEndTurn',
    PlayerAbandonGame = 'playerAbandonGame',
    PlayerAbandoned = 'playerAbandoned',
    PlayerJoinInGameSession = 'playerJoinInGameSession',
    PlayerJoinedInGameSession = 'playerJoinedInGameSession',
    PlayerLeaveInGameSession = 'playerLeaveInGameSession',
    PlayerLeftInGameSession = 'playerLeftInGameSession',
    PlayerMove = 'playerMove',
    PlayerMoved = 'playerMoved',
    PlayerCombatAction = 'playerCombatAction',
    PlayerCombatResult = 'playerCombatResult',
    PlayerUpdated = 'playerUpdated',
    PlayerActionUsed = 'playerAvailableActionsUpdated',
    PlayerReachableTiles = 'playerReachableTiles',
    PlayerAvailableActions = 'playerAvailableActions',
    PlayerSanctuaryRequest = 'playerSanctuaryRequest',
    PlayerSanctuaryAction = 'playerSanctuaryAction',
    PlayerBonusesChanged = 'playerBonusesChanged',
    PlayerBoardBoat = 'playerBoardBoat',
    PlayerBoardedBoat = 'playerBoardedBoat',
    PlayerDisembarkBoat = 'playerDisembarkBoat',
    PlayerDisembarkedBoat = 'playerDisembarkedBoat',

    OpenSanctuary = 'openSanctuary',
    SanctuaryActionFailed = 'sanctuaryActionFailed',
    SanctuaryActionSuccess = 'sanctuaryActionSuccess',

    ToggleAdminMode = 'toggleAdminMode',
    AdminModeToggled = 'adminModeToggled',
    PlayerTeleport = 'playerTeleport',
    PlayerTeleported = 'playerTeleported',

    ToggleDoorAction = 'toggleDoorAction',
    AttackPlayerAction = 'attackPlayerAction',
    CombatChoice = 'combatChoice',
    CombatPostureSelected = 'combatPostureSelected',
    CombatStarted = 'combatStarted',
    CombatNotification = 'combatNotification',
    CombatTimerUpdate = 'combatTimerUpdate',
    CombatTileEffect = 'combatTileEffect',
    CombatNewRoundStarted = 'combatNewRoundStarted',
    CombatVictory = 'combatVictory',
    CombatEnded = 'combatEnded',
    CombatAbandon = 'combatAbandon',
    CombatCountChanged = 'combatCountChanged',
    CombatWinsChanged = 'combatWinsChanged',
    CombatLossesChanged = 'combatLossesChanged',
    CombatDrawsChanged = 'combatDrawsChanged',
    CombatTimerRestart = 'combatTimerRestart',
    DoorToggled = 'doorToggled',
    PlayerHealthChanged = 'playerHealthChanged',
    LeftInGameSessionAck = 'leftInGameSessionAck',

    PlaceablePositionUpdated = 'placeablePositionUpdated',
>>>>>>> origin/dev
}
