export enum InGameEvents {
    GameStart = 'gameStart',
    GameStarted = 'gameStarted',
    GameOver = 'gameOver',
    GameForceStopped = 'gameForceStopped',

    TurnStart = 'turnStart',
    TurnStarted = 'turnStarted',
    TurnEnd = 'turnEnd',
    TurnEnded = 'turnEnded',
    TurnTransitionEnded = 'turnTransitionEnded',
    TurnTimeout = 'turnTimeout',
    TurnForcedEnd = 'turnForcedEnd',
    TurnManualEnd = 'turnManualEnd',

    PlayerEndTurn = 'playerEndTurn',
    PlayerJoinInGameSession = 'playerJoinInGameSession',
    PlayerJoinedInGameSession = 'playerJoinedInGameSession',
    PlayerLeaveInGameSession = 'playerLeaveInGameSession',
    PlayerLeftInGameSession = 'playerLeftInGameSession',
    PlayerMove = 'playerMove',
    PlayerMoved = 'playerMoved',
    PlayerCombatAction = 'playerCombatAction',
    PlayerCombatResult = 'playerCombatResult',
    PlayerUpdated = 'playerUpdated',
    PlayerActionUsed = 'playerAvailableActionsUpdated',
    PlayerReachableTiles = 'playerReachableTiles',
    PlayerAvailableActions = 'playerAvailableActions',
    ToggleDoorAction = 'toggleDoorAction',
    AttackPlayerAction = 'attackPlayerAction',
    CombatChoice = 'combatChoice',
    CombatStarted = 'combatStarted',
    CombatNotification = 'combatNotification',
    CombatTimerUpdate = 'combatTimerUpdate',
    CombatEnded = 'combatEnded',
    DoorToggled = 'doorToggled',

    LeftInGameSessionAck = 'leftInGameSessionAck',
}
