export const DEFAULT_TURN_DURATION = 30000;
export const DEFAULT_TURN_TRANSITION_DURATION = 3000;
export const ARRAY_SHUFFLE_FACTOR = 0.5;
export const MILLISECONDS_PER_SECOND = 1000;
export const COMBAT_DURATION = 5000;
