/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateTileDto } from './createTileDto';
import { CreatePlaceableDto } from './createPlaceableDto';


export interface CreateGameDto { 
    size: CreateGameDto.SizeEnum;
    mode: CreateGameDto.ModeEnum;
    name: string;
    description: string;
    visibility?: boolean;
    /**
     * Sparse tiles: only those different from BASE
     */
    tiles: Array<CreateTileDto>;
    objects: Array<CreatePlaceableDto>;
}
export namespace CreateGameDto {
    export const SizeEnum = {
        NUMBER_10: 10,
        NUMBER_15: 15,
        NUMBER_20: 20
    } as const;
    export type SizeEnum = typeof SizeEnum[keyof typeof SizeEnum];
    export const ModeEnum = {
        Classic: 'classic',
        CaptureTheFlag: 'capture-the-flag'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


