/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePlaceableDto { 
    kind: CreatePlaceableDto.KindEnum;
    x: number;
    y: number;
    orientation?: CreatePlaceableDto.OrientationEnum;
}
export namespace CreatePlaceableDto {
    export const KindEnum = {
        Start: 'START',
        Flag: 'FLAG',
        Heal: 'HEAL',
        Fight: 'FIGHT',
        Boat: 'BOAT'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
    export const OrientationEnum = {
        N: 'N',
        E: 'E',
        S: 'S',
        W: 'W'
    } as const;
    export type OrientationEnum = typeof OrientationEnum[keyof typeof OrientationEnum];
}


