/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GamePreviewDto {
    id: string;
    name: string;
    size: GamePreviewDto.SizeEnum;
    mode: GamePreviewDto.ModeEnum;
    description: string;
    lastModified: string;
    visibility: boolean;
    gridPreviewUrl: string;
}
export namespace GamePreviewDto {
    export const SizeEnum = {
        NUMBER_10: 10,
        NUMBER_15: 15,
        NUMBER_20: 20,
    } as const;
    export type SizeEnum = (typeof SizeEnum)[keyof typeof SizeEnum];
    export const ModeEnum = {
        Classic: 'classic',
        CaptureTheFlag: 'capture-the-flag',
    } as const;
    export type ModeEnum = (typeof ModeEnum)[keyof typeof ModeEnum];
}
