/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameEditorPlaceableDto { 
    id: string;
    kind: GameEditorPlaceableDto.KindEnum;
    x: number;
    y: number;
    placed: boolean;
}
export namespace GameEditorPlaceableDto {
    export const KindEnum = {
        Start: 'START',
        Flag: 'FLAG',
        Heal: 'HEAL',
        Fight: 'FIGHT',
        Boat: 'BOAT'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
}


