/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameEditorTileDto } from './gameEditorTileDto';
import { GameEditorPlaceableDto } from './gameEditorPlaceableDto';

export interface PatchGameEditorDto {
    name?: string;
    description?: string;
    size?: PatchGameEditorDto.SizeEnum;
    mode?: PatchGameEditorDto.ModeEnum;
    gridPreviewUrl?: string;
    tiles?: Array<GameEditorTileDto>;
    objects?: Array<GameEditorPlaceableDto>;
}
export namespace PatchGameEditorDto {
    export const SizeEnum = {
        NUMBER_10: 10,
        NUMBER_15: 15,
        NUMBER_20: 20,
    } as const;
    export type SizeEnum = (typeof SizeEnum)[keyof typeof SizeEnum];
    export const ModeEnum = {
        Classic: 'classic',
        CaptureTheFlag: 'capture-the-flag',
    } as const;
    export type ModeEnum = (typeof ModeEnum)[keyof typeof ModeEnum];
}
