/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReadTileDto { 
    x: number;
    y: number;
    kind: ReadTileDto.KindEnum;
    /**
     * For DOOR only
     */
    open?: boolean;
    /**
     * For TELEPORT only
     */
    endpointId?: number;
    id: string;
}
export namespace ReadTileDto {
    export const KindEnum = {
        Water: 'WATER',
        Wall: 'WALL',
        Ice: 'ICE',
        Door: 'DOOR',
        Base: 'BASE',
        Teleport: 'TELEPORT'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
}


