/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReadTileDto } from './readTileDto';
import { ReadPlaceableDto } from './readPlaceableDto';


export interface ReadGameDto { 
    size: ReadGameDto.SizeEnum;
    mode: ReadGameDto.ModeEnum;
    name: string;
    description: string;
    visibility?: boolean;
    /**
     * Sparse tiles: only those different from BASE
     */
    tiles: Array<ReadTileDto>;
    objects: Array<ReadPlaceableDto>;
    id: string;
    lastModified: string;
}
export namespace ReadGameDto {
    export const SizeEnum = {
        NUMBER_10: 10,
        NUMBER_15: 15,
        NUMBER_20: 20
    } as const;
    export type SizeEnum = typeof SizeEnum[keyof typeof SizeEnum];
    export const ModeEnum = {
        Classic: 'classic',
        CaptureTheFlag: 'capture-the-flag'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


