/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SaveTileDto } from './saveTileDto';
import { SavePlaceableDto } from './savePlaceableDto';


export interface SaveGameDto { 
    /**
     * Game ID when saving an edit; omitted/ignored for creation.
     */
    id?: string;
    size: SaveGameDto.SizeEnum;
    mode: SaveGameDto.ModeEnum;
    name: string;
    description: string;
    visibility?: boolean;
    /**
     * Complete list of non-BASE tiles (replaces existing).
     */
    tiles: Array<SaveTileDto>;
    /**
     * Complete list of placed objects (replaces existing).
     */
    objects: Array<SavePlaceableDto>;
}
export namespace SaveGameDto {
    export const SizeEnum = {
        NUMBER_10: 10,
        NUMBER_15: 15,
        NUMBER_20: 20
    } as const;
    export type SizeEnum = typeof SizeEnum[keyof typeof SizeEnum];
    export const ModeEnum = {
        Classic: 'classic',
        CaptureTheFlag: 'capture-the-flag'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


