export default (tsParser, tsPlugin) => [
    {
        files: ['**/*.js', '**/*.ts'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                console: 'readonly',
                process: 'readonly',
                Buffer: 'readonly',
                __dirname: 'readonly',
                __filename: 'readonly',
                module: 'readonly',
                require: 'readonly',
                exports: 'readonly',
                global: 'readonly',
            },
        },
        ignores: ['projects/**/*', 'node_modules/**/*', 'out/**/*', 'coverage/**/*'],
        rules: {
            'no-console': 'error',
            'no-debugger': 'error',
            'no-var': 'error',
            'prefer-const': 'error',
            'quotes': ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
            'semi': ['error', 'always'],
            'eqeqeq': ['error', 'smart'],
            'no-duplicate-imports': 'error',
            'no-multiple-empty-lines': 'error',
            'complexity': ['error', 15],
            'max-len': ['error', { code: 150, ignoreComments: true, ignoreTrailingComments: true }],
            'max-lines': ['error', { max: 350, skipBlankLines: true, skipComments: true }],
            'max-params': ['error', 5],
            'max-classes-per-file': ['error', 3],
            'no-bitwise': 'error',
            'no-caller': 'error',
            'no-cond-assign': 'error',
            'no-empty': 'error',
            'no-eval': 'error',
            'no-invalid-this': 'error',
            'no-restricted-imports': ['error', { 'patterns': ['../*'] }],
            'no-fallthrough': 'error',
            'no-new-wrappers': 'error',
            'no-throw-literal': 'error',
            'no-undef-init': 'error',
            'no-unsafe-finally': 'error',
            'no-unused-labels': 'error',
            'object-shorthand': 'error',
            'one-var': ['error', 'never'],
            'one-var-declaration-per-line': 'error',
            'quote-props': ['error', 'consistent-as-needed'],
            'radix': 'error',
            'use-isnan': 'error',
            'guard-for-in': 'error',
            'no-inline-comments': 'warn',
        },
    },
    {
        files: ['**/*.ts'],
        languageOptions: {
            parser: tsParser,
            parserOptions: {
                project: ['./tsconfig.json'],
                createDefaultProgram: true,
            },
        },
        plugins: { '@typescript-eslint': tsPlugin },
        rules: {
            '@typescript-eslint/no-unused-vars': 'error',
            '@typescript-eslint/dot-notation': 'error',
            '@typescript-eslint/no-unused-expressions': 'error',
            // Added lint rules for code quality - COMMENTED OUT
            // '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
            // '@typescript-eslint/no-unnecessary-condition': 'warn',
            '@typescript-eslint/no-magic-numbers': [
                'error',
                {
                    ignore: [-1, 0, 1, 2],
                    ignoreArrayIndexes: true,
                    ignoreClassFieldInitialValues: true,
                    ignoreEnums: true,
                    ignoreReadonlyClassProperties: true,
                },
            ],
            '@typescript-eslint/array-type': ['error', { default: 'array' }],
            '@typescript-eslint/explicit-member-accessibility': ['error', { accessibility: 'no-public' }],
            '@typescript-eslint/prefer-readonly': 'warn',
            '@typescript-eslint/no-explicit-any': ['error', { fixToUnknown: true }],
            '@typescript-eslint/no-inferrable-types': [
                'error',
                { ignoreParameters: true, ignoreProperties: true },
            ],
            '@typescript-eslint/prefer-for-of': 'error',
            '@typescript-eslint/prefer-function-type': 'error',
            "@typescript-eslint/consistent-type-assertions": "error",
            "@typescript-eslint/no-empty-function": "error",
            "@typescript-eslint/no-misused-new": "error",
            "@typescript-eslint/no-non-null-assertion": "error",
            "@typescript-eslint/no-shadow": ["error", { "hoist": "all" }],
            "@typescript-eslint/no-require-imports": "error",
            "@typescript-eslint/no-empty-object-type": "error",
            "@typescript-eslint/no-unsafe-function-type": "error",
            "@typescript-eslint/no-wrapper-object-types": "error",
            "@typescript-eslint/naming-convention": [
                "error",
                {
                    "format": ["camelCase"],
                    "leadingUnderscore": "allow",
                    "selector": "default",
                    "trailingUnderscore": "allow",
                    "filter": { "regex": "^(_id|__v)$", "match": false }
                },
                {
                    "format": ["camelCase", "UPPER_CASE"],
                    "selector": "variable",
                    "trailingUnderscore": "allow",
                },
                {
                    "format": ["PascalCase"],
                    "selector": "typeLike"
                },
                {
                    "format": ["PascalCase"],
                    "selector": "enumMember"
                }
            ],
            // "@typescript-eslint/explicit-function-return-type": "warn",
            "@typescript-eslint/no-unnecessary-type-assertion": "warn"
        },
    },
    {
        files: ['**/*.spec.ts'],
        rules: { '@typescript-eslint/dot-notation': 'off' },
    },
];
