/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VirtualPlayerType } from '@common/enums/virtual-player-type.enum';

export interface AddVirtualPlayerDto {
    sessionId: string;
    virtualPlayerType: VirtualPlayerType;
}
