/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvailableActionType } from '@common/enums/available-action-type.enum';

export interface AvailableActionDto {
    type: AvailableActionType;
    x: number;
    y: number;
}
