/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvailableActionDto } from './available-action-dto';

export interface AvailableActionsDto {
    availableActions: Array<AvailableActionDto>;
}
