/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvatarAssignmentDto } from './avatar-assignment-dto';


export interface AvatarAssignmentsUpdatedDto { 
    avatarAssignments: Array<AvatarAssignmentDto>;
}

