/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Avatar } from '@common/enums/avatar.enum';


export interface AvatarAssignmentDto { 
    avatar: Avatar;
    chosenBy: string | null;
}

