/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CombatVictoryDto { 
    playerAId: string;
    playerBId: string;
    winnerId: string | null;
    abandon: boolean;
}

