/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CombatPosture } from '@common/enums/combat-posture.enum';

export interface CombatPostureSelectedDto {
    playerId: string;
    posture: CombatPosture;
}
