/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameMode } from '@common/enums/game-mode.enum';
import { PlayerDto } from './player-dto';


export interface CreateSessionDto { 
    gameId: string;
    maxPlayers: number;
    mode: GameMode;
    player: PlayerDto;
}

