/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSessionDto { 
    mapSize: number;
    player: object;
    map: Array<string>;
    itemContainers: Array<string>;
}

