/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GameEditorTileDto {
    kind: GameEditorTileDto.KindEnum;
    x: number;
    y: number;
    open?: boolean;
    teleportChannel?: number;
}
export namespace GameEditorTileDto {
    export const KindEnum = {
        Water: 'WATER',
        Wall: 'WALL',
        Ice: 'ICE',
        Door: 'DOOR',
        Base: 'BASE',
        Teleport: 'TELEPORT',
    } as const;
    export type KindEnum = (typeof KindEnum)[keyof typeof KindEnum];
}
