/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GlobalStatisticsDto } from './global-statistics-dto';
import { PlayerStatisticsDto } from './player-statistics-dto';

export interface GameStatisticsDto {
    winnerId: string;
    winnerName: string;
    playersStatistics: Array<PlayerStatisticsDto>;
    globalStatistics: GlobalStatisticsDto;
}
