/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameMode } from '@common/enums/game-mode.enum';
import { MapSize } from '@common/enums/map-size.enum';


export interface GamePreviewDto { 
    id: string;
    name: string;
    size: MapSize;
    mode: GameMode;
    description: string;
    lastModified: string;
    visibility: boolean;
    gridPreviewUrl: string;
    draft: boolean;
}

