/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TileKind } from '@common/enums/tile.enum';

export interface GameEditorTileDto {
    kind: TileKind;
    x: number;
    y: number;
    open?: boolean;
    teleportChannel?: number;
}
