/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameEditorTileDto } from './game-editor-tile-dto';
import { GameEditorPlaceableDto } from './game-editor-placeable-dto';


export interface GameEditorDto { 
    id: string;
    name: string;
    description: string;
    size: GameEditorDto.SizeEnum;
    mode: GameEditorDto.ModeEnum;
    tiles: Array<GameEditorTileDto>;
    objects: Array<GameEditorPlaceableDto>;
    gridPreviewUrl: string;
    lastModified: string;
}
export namespace GameEditorDto {
    export const SizeEnum = {
        NUMBER_10: 10,
        NUMBER_15: 15,
        NUMBER_20: 20
    } as const;
    export type SizeEnum = typeof SizeEnum[keyof typeof SizeEnum];
    export const ModeEnum = {
        Classic: 'classic',
        CaptureTheFlag: 'capture-the-flag'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


