/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameInitDto { 
    mapSize: GameInitDto.MapSizeEnum;
}
export namespace GameInitDto {
    export const MapSizeEnum = {
        NUMBER_10: 10,
        NUMBER_15: 15,
        NUMBER_20: 20
    } as const;
    export type MapSizeEnum = typeof MapSizeEnum[keyof typeof MapSizeEnum];
}


