/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GlobalStatisticsDto {
    gameDuration: string;
    totalTurns: number;
    tilesVisitedPercentage: number;
    totalTeleportations: number;
    doorsManipulatedPercentage: number;
    sanctuariesUsedPercentage: number;
    flagHoldersCount: number;
}
