/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMessageDto } from './chat-message-dto';


export interface LoadMessagesDto { 
    messages: Array<ChatMessageDto>;
}

