/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaceableKind } from '@common/enums/placeable-kind.enum';

export interface OpenSanctuaryDto {
    kind: PlaceableKind;
    x: number;
    y: number;
}
