/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameEditorTileDto } from './game-editor-tile-dto';
import { GameMode } from '@common/enums/game-mode.enum';
import { GameEditorPlaceableDto } from './game-editor-placeable-dto';
import { MapSize } from '@common/enums/map-size.enum';


export interface PatchGameEditorDto { 
    name?: string;
    description?: string;
    size?: MapSize;
    mode?: GameMode;
    gridPreviewUrl?: string;
    tiles?: Array<GameEditorTileDto>;
    objects?: Array<GameEditorPlaceableDto>;
}

