/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaceableKind } from '@common/enums/placeable-kind.enum';
import { Orientation } from '@common/enums/orientation.enum';

export interface PlaceablePositionUpdatedDto {
    _id?: string;
    kind: PlaceableKind;
    x: number;
    y: number;
    placed: boolean;
    orientation?: Orientation;
}
