/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Orientation } from '@common/enums/orientation.enum';

export interface PlayerMoveDto {
    sessionId: string;
    orientation: Orientation;
}
