/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PlayerStatisticsDto {
    name: string;
    combatCount: number;
    combatWins: number;
    combatLosses: number;
    healthLost: number;
    healthDealt: number;
    tilesVisitedPercentage: number;
}
