/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Dice } from '@common/enums/dice.enum';
import { Avatar } from '@common/enums/avatar.enum';

export interface PlayerDto {
    id: string;
    name: string;
    avatar: Avatar | null;
    isAdmin: boolean;
    attackDice: Dice;
    defenseDice: Dice;
    baseHealth: number;
    healthBonus: number;
    health: number;
    maxHealth: number;
    baseAttack: number;
    attackBonus: number;
    baseDefense: number;
    defenseBonus: number;
    baseSpeed: number;
    speedBonus: number;
    speed: number;
    actionsRemaining: number;
    hasCombatBonus: boolean;
    boatSpeedBonus: number;
    boatSpeed: number;
}
