/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Dice } from '@common/enums/dice.enum';
import { Avatar } from '@common/enums/avatar.enum';


export interface PlayerDto { 
    id: string;
    name: string;
    avatar: Avatar | null;
    isAdmin: boolean;
    attack: Dice;
    defense: Dice;
    speed: number;
    health: number;
}

