/**
 * Cadriciel Serveur
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaceableKind } from '@common/enums/placeable-kind.enum';

export interface SanctuaryActionSuccessDto {
    kind: PlaceableKind;
    x: number;
    y: number;
    success: boolean;
    addedHealth?: number;
    addedDefense?: number;
    addedAttack?: number;
}
