/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionPlayerDto } from './session-player-dto';


export interface SessionPlayersUpdatedDto { 
    players: Array<SessionPlayerDto>;
}

