/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeleportTilesDto } from './teleport-tiles-dto';


export interface TeleportChannelDto { 
    channelNumber: number;
    tiles: TeleportTilesDto;
}

