/**
 * Cadriciel Serveur
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeleportTileCoordinatesDto } from './teleport-tile-coordinates-dto';


export interface TeleportTilesDto { 
    a?: TeleportTileCoordinatesDto;
    b?: TeleportTileCoordinatesDto;
}

