export const VIRTUAL_PLAYER_THINKING_DELAY_MIN_MS = 1500;
export const VIRTUAL_PLAYER_THINKING_DELAY_MAX_MS = 4000;
export const VIRTUAL_PLAYER_MOVEMENT_DELAY_MS = 500;
export const VIRTUAL_PLAYER_ACTION_DELAY_MS = 1000;
