export const DAMAGE_DISPLAY_DURATION_MS = 2000;
export const VICTORY_NOTIFICATION_DURATION_MS = 3000;
export const COMBAT_TOAST_DURATION_MS = 5000;
export const COMBAT_ROUND_DURATION_SECONDS = 5;
export const COMBAT_POSTURE_BONUS = 2;
export const HEALTH_LOW_THRESHOLD = 25;
export const HEALTH_MEDIUM_THRESHOLD = 50;
export const SANCTUARY_SUCCESS_RATE = 50;

