export const VALIDATION_CONSTANTS = {
    NAME_MIN_LENGTH: 5,
    NAME_MAX_LENGTH: 50,
    DESCRIPTION_MIN_LENGTH: 10,
    DESCRIPTION_MAX_LENGTH: 250,
    WHITESPACE_PATTERN: /\s/g,
    NAME_INVALID_CHARS_PATTERN: /[^a-zA-Z0-9\s\-']/g,
} as const;
